services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard
    ports:
      - 5432:5432
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  fastapi:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      MODULE_NAME: main
      VARIABLE_NAME: app
      DATABASE_URL: postgresql://admin:password@db:5432/dashboard
      POETRY_VIRTUALENVS_CREATE: false
      POETRY_NO_INTERACTION: 1
    command: >
      bash -c "
        pip install --no-cache-dir poetry &&
        poetry install --no-root --only main &&
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  pgdata:
